-- DEEP-SIGN initial schema
-- Run this once in your Supabase project's SQL Editor.
--
-- Notes:
--   * Auth is handled entirely by Supabase Auth (auth.users table is built-in).
--   * Detections are scoped per-user via Row-Level Security so users can never
--     read or write someone else's history, even with a stolen anon key.

create table if not exists public.detections (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  sign        text not null,
  confidence  numeric(5, 3) not null check (confidence >= 0 and confidence <= 1),
  created_at  timestamptz not null default now()
);

create index if not exists detections_user_recent_idx
  on public.detections (user_id, created_at desc);

-- Lock the table down.
alter table public.detections enable row level security;

-- Each authenticated user can read their own detections.
drop policy if exists "read own detections" on public.detections;
create policy "read own detections"
  on public.detections for select
  using (auth.uid() = user_id);

-- Each authenticated user can insert detections, but only as themselves.
drop policy if exists "insert own detections" on public.detections;
create policy "insert own detections"
  on public.detections for insert
  with check (auth.uid() = user_id);

-- Each authenticated user can delete their own detections (used by "Clear all").
drop policy if exists "delete own detections" on public.detections;
create policy "delete own detections"
  on public.detections for delete
  using (auth.uid() = user_id);
